
CREATE TABLE DATOS_DISPOSITIVOS (
    IDUNIDAD VARCHAR (20) PRIMARY KEY,
    CODIMARCA SMALLINT REFERENCES MARCAS(CODIGO) ON DELETE RESTRICT, 
    CODILINEA SMALLINT REFERENCES LINEAS(CODIGO) ON DELETE RESTRICT,
    IMEI VARCHAR (20) DEFAULT 'NO APLICA', /* gps.imei */
    TARJETA_SIM VARCHAR (30) DEFAULT 'NO APLICA', /* serial of the sim */
    NRO_MOVIL VARCHAR (11) DEFAULT 'NO APLICA', /* phone number */
    OPERADORMOVIL REFERENCES OPERADOR_MOVIL(id) ON DELETE RESTRICT,
    OPERADOR_SATELITAL REFERENCES OPERADOR_SATELITAL(id) ON DELETE RESTRICT,
    OBSERVACION REFERENCES OBSERVACION_DISPOSITIVO(id) ON DELETE RESTRICT,
    SERIE_DISPOSITIVO VARCHAR (50) DEFAULT 'NO APLICA' 
);


CREATE TABLE DATOS_MAQUINAS (
);


CREATE TABLE RELACION_MAQUINAS_DISPOSITIVO (
);


/* table: OK - Create the insert */
CREATE TABLE MARCAS (
    CODIGO SMALLINT PRIMARY KEY,
    DESCRIPCION VARCHAR (50) NOT NULL
);
/*INSERT INTO MARCAS VALUES (0, 'NO REPORTADA'); */

/* table OK - Create the insert */
CREATE TABLE LINEAS (
    CODIGO SMALLINT PRIMARY KEY,
    DESCRIPCION VARCHAR (50) NOT NULL
);
/*INSERT INTO LINEAS VALUES (1, '1700'); */

/* table OK */
CREATE TABLE OPERADOR_MOVIL (
    id SERIAL PRIMARY KEY,
    description VARCHAR (30) NOT NULL
);
INSERT INTO OPERADOR_MOVIL VALUES ('Claro');
INSERT INTO OPERADOR_MOVIL VALUES ('Movistar');

/* table OK */
CREATE TABLE OPERADOR_SATELITAL (
    id SERIAL PRIMARY KEY,
    description VARCHAR (30) NOT NULL
);
INSERT INTO OPERADOR_SATELITAL VALUES ('No Aplica');

CREATE TABLE OBSERVACION_DISPOSITIVO (
    id SERIAL PRIMARY KEY,
    description VARCHAR (50)
);
INSERT INTO OBSERVACION_DISPOSITIVO VALUES ('BUEN ESTADO');

